
import javax.swing.JLabel;

public class tateti extends javax.swing.JFrame {
     public static void main (String[] args)
    {
String turno="X";
JLabel lbs[]= new JLabel[9];
int vs[][]={
    {1,2,3},
    {4,5,6},
    {7,8,9},
    {1,4,7},
    {2,5,8},
    {3,6,9},
    {1,5,9},
    {3,5,7}
        
};

    
    
    public tateti() {
    initComponents();
       
    this.setLocationRelativeTo(null);
    lbs[0]=jLabel1111;
    lbs[1]=jLabel22;
    lbs[2]=jLabel33;
    lbs[3]=jLabel44;
    lbs[4]=jLabel55;
    lbs[5]=jLabel66;
    lbs[6]=jLabel77;
    lbs[7]=jLabel15;
    lbs[8]=jLabel99;
    
}

 
 
 private void jLabel111MousePressed(java.awt.event.MouseEvent evt){
    presionar(1);
}
private void jLabel22MousePressed(java.awt.event.MouseEvent evt){
    presionar(2);
}
private void jLabel33MousePressed(java.awt.event.MouseEvent evt){
    presionar(3);
}
private void jLabel44MousePressed(java.awt.event.MouseEvent evt){
    presionar(4);
}
private void jLabel55MousePressed(java.awt.event.MouseEvent evt){
    presionar(5);
}
private void jLabel66MousePressed(java.awt.event.MouseEvent evt){
    presionar(6);
}
private void jLabel77MousePressed(java.awt.event.MouseEvent evt){
    presionar(7);
}
private void jLabel15MousePressed(java.awt.event.MouseEvent evt){
    presionar(8);
}
private void jLabel99MousePressed(java.awt.event.MouseEvent evt){
    presionar(9);
}
 public void presionar(int casilla){
    if(lbs[casilla-1].getText().equals("")){
    lbs[casilla-1].setText(turno);
    cambiarTurno();
    
    
}
}
   public void cambiarTurno(){
        if (turno.equals("X")){
            turno="O";   
        }else{
            turno="X";
        }
    }
   
public void comprobarGanador(){
    for (int i = 0; i < vs.length; i++) {
        if(lbs[vs[i][0]-1].getText().equals("X")&&
                lbs[vs[i][1]-1].getText().equals("X")&&
                        lbs[vs[i][2]-1].getText().equals("X")){
        lbs[vs[i][0]-1].setBackground(Color.green);
        lbs[vs[i][1]-1].setBackground(Color.green);
        lbs[vs[i][2]-1].setBackground(Color.green);
    
                        
        System.out.println("gano X");
    }
      if(lbs[vs[i][0]-1].getText().equals("O")&&
                lbs[vs[i][1]-1].getText().equals("O")&&
                        lbs[vs[i][2]-1].getText().equals("O")){
        lbs[vs[i][0]-1].setBackground(Color.green);
        lbs[vs[i][1]-1].setBackground(Color.green);
        lbs[vs[i][2]-1].setBackground(Color.green);
    
                        
        System.out.println("gano O");
    }               
    
}
 




  
    

    /**z
     * Creates new form tateti
     */
   

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1111 = new javax.swing.JLabel();
        jLabelDos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelTRes = new javax.swing.JPanel();
        jLabelTres = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelCuatro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanelCinco = new javax.swing.JPanel();
        jLabelCinco = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabelSiete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabelSeis = new javax.swing.JPanel();
        jLabelSix = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabelOcho = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelNueve = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel111.setBackground(new java.awt.Color(255, 255, 255));
        jLabel111.setForeground(new java.awt.Color(0, 0, 0));
        jLabel111.setFont(new java.awt.Font("Niagara Engraved", 2, 48)); // NOI18N

        jLabel3.setText(" ");

        jLabel1111.setText("x");

        javax.swing.GroupLayout jLabel111Layout = new javax.swing.GroupLayout(jLabel111);
        jLabel111.setLayout(jLabel111Layout);
        jLabel111Layout.setHorizontalGroup(
            jLabel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel111Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jLabel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabel111Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jLabel111Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLabel111Layout.setVerticalGroup(
            jLabel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel111Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLabel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1111, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabelDos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setText("x");

        javax.swing.GroupLayout jLabelDosLayout = new javax.swing.GroupLayout(jLabelDos);
        jLabelDos.setLayout(jLabelDosLayout);
        jLabelDosLayout.setHorizontalGroup(
            jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelDosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelDosLayout.setVerticalGroup(
            jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelDosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTRes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTRes.setForeground(new java.awt.Color(0, 0, 0));

        jLabelTres.setText(" ");

        jLabel33.setText("x");

        javax.swing.GroupLayout jLabelTResLayout = new javax.swing.GroupLayout(jLabelTRes);
        jLabelTRes.setLayout(jLabelTResLayout);
        jLabelTResLayout.setHorizontalGroup(
            jLabelTResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelTResLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jLabelTResLayout.setVerticalGroup(
            jLabelTResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelTResLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jLabelTResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelTResLayout.createSequentialGroup()
                        .addComponent(jLabelTres)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelTResLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        jLabelCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCuatro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setText(" ");

        jLabel44.setText("x");

        javax.swing.GroupLayout jLabelCuatroLayout = new javax.swing.GroupLayout(jLabelCuatro);
        jLabelCuatro.setLayout(jLabelCuatroLayout);
        jLabelCuatroLayout.setHorizontalGroup(
            jLabelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelCuatroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelCuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13))
        );
        jLabelCuatroLayout.setVerticalGroup(
            jLabelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelCuatroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLabelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelCinco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCinco.setForeground(new java.awt.Color(0, 0, 0));

        jLabelCinco.setText(" ");

        jLabel55.setText("x");

        javax.swing.GroupLayout jPanelCincoLayout = new javax.swing.GroupLayout(jPanelCinco);
        jPanelCinco.setLayout(jPanelCincoLayout);
        jPanelCincoLayout.setHorizontalGroup(
            jPanelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCincoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelCinco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCincoLayout.setVerticalGroup(
            jPanelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCincoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCinco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSiete.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSiete.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setText("   ");

        jLabel77.setText("x");

        javax.swing.GroupLayout jLabelSieteLayout = new javax.swing.GroupLayout(jLabelSiete);
        jLabelSiete.setLayout(jLabelSieteLayout);
        jLabelSieteLayout.setHorizontalGroup(
            jLabelSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSieteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jLabelSieteLayout.setVerticalGroup(
            jLabelSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSieteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLabelSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabelSeis.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeis.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSix.setText(" ");

        jLabel66.setText("x");

        javax.swing.GroupLayout jLabelSeisLayout = new javax.swing.GroupLayout(jLabelSeis);
        jLabelSeis.setLayout(jLabelSeisLayout);
        jLabelSeisLayout.setHorizontalGroup(
            jLabelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSeisLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel66)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSix)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelSeisLayout.setVerticalGroup(
            jLabelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSeisLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLabelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSix)
                    .addComponent(jLabel66))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelOcho.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOcho.setForeground(new java.awt.Color(0, 0, 0));

        jLabel88.setText("  ");

        jLabel15.setText("x");

        javax.swing.GroupLayout jLabelOchoLayout = new javax.swing.GroupLayout(jLabelOcho);
        jLabelOcho.setLayout(jLabelOchoLayout);
        jLabelOchoLayout.setHorizontalGroup(
            jLabelOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelOchoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel88)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jLabelOchoLayout.setVerticalGroup(
            jLabelOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelOchoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLabelOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel88))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNueve.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNueve.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setText(" ");

        jLabel99.setText("x");

        javax.swing.GroupLayout jLabelNueveLayout = new javax.swing.GroupLayout(jLabelNueve);
        jLabelNueve.setLayout(jLabelNueveLayout);
        jLabelNueveLayout.setHorizontalGroup(
            jLabelNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelNueveLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelNueveLayout.setVerticalGroup(
            jLabelNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelNueveLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLabelNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel99))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel111, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSeis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel111, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jLabel111;
    private javax.swing.JLabel jLabel1111;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel jLabelCinco;
    private javax.swing.JPanel jLabelCuatro;
    private javax.swing.JPanel jLabelDos;
    private javax.swing.JPanel jLabelNueve;
    private javax.swing.JPanel jLabelOcho;
    private javax.swing.JPanel jLabelSeis;
    private javax.swing.JPanel jLabelSiete;
    private javax.swing.JLabel jLabelSix;
    private javax.swing.JPanel jLabelTRes;
    private javax.swing.JLabel jLabelTres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCinco;
    // End of variables declaration//GEN-END:variables
}
}
}