
import javax.swing.JLabel;

//import javax.swing.JLabel;

public class TaTeTijuego extends javax.swing.JFrame {

    
String turno="X";
JLabel lbs[]= new JLabel[9];

public TaTeTijuego() {
    
    initComponents();
    this.setLocationRelativeTo(null);
    lbs[0]=jLabelUno;
    lbs[1]=jLabelDos;
    lbs[2]=jLabelTres;
    lbs[3]=jLabelCuatro;
    lbs[4]=jLabelCinco;
    lbs[5]=jLabelSix;
    lbs[6]=jLabelSiete;
    lbs[7]=jLabelOcho;
    lbs[8]=jLabelNueve;
    
}

 public TaTeTijuego() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
 
 private void jLabelUnoMousePressed(java.awt.event.MouseEvent evt){
    presionar(1);
}
private void jLabelDosMousePressed(java.awt.event.MouseEvent evt){
    presionar(2);
}
private void jLabelTresMousePressed(java.awt.event.MouseEvent evt){
    presionar(3);
}
private void jLabelCuatroMousePressed(java.awt.event.MouseEvent evt){
    presionar(4);
}
private void jLabelCincoMousePressed(java.awt.event.MouseEvent evt){
    presionar(5);
}
private void jLabelSixMousePressed(java.awt.event.MouseEvent evt){
    presionar(6);
}
private void jLabelSieteMousePressed(java.awt.event.MouseEvent evt){
    presionar(7);
}
private void jLabelOchoMousePressed(java.awt.event.MouseEvent evt){
    presionar(8);
}
private void jLabelNueveMousePressed(java.awt.event.MouseEvent evt){
    presionar(9);
}
 public void presionar(int casilla){
    if(lbs[casilla-1].getText().equals("")){
    lbs[casilla-1].setText(turno);
    cambiarTurno();
    
    
}
}
   public void cambiarTurno(){
        if (turno.equals("X")){
            turno="O";
            
        }else{
            turno="X";
        }
    }
   

 




  
    

    /**
     * Creates new form tateti
     */
   

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTRes = new javax.swing.JPanel();
        jLabelTres = new javax.swing.JLabel();
        jLabelCuatro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelCinco = new javax.swing.JPanel();
        jLabelCinco = new javax.swing.JLabel();
        jLabelSiete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelSeis = new javax.swing.JPanel();
        jLabelSix = new javax.swing.JLabel();
        jLabelOcho = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNueve = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabelUno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUno.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUno.setFont(new java.awt.Font("Niagara Engraved", 2, 48)); // NOI18N

        jLabel3.setText(" ");

        javax.swing.GroupLayout jLabelUnoLayout = new javax.swing.GroupLayout(jLabelUno);
        jLabelUno.setLayout(jLabelUnoLayout);
        jLabelUnoLayout.setHorizontalGroup(
            jLabelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelUnoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelUnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jLabelUnoLayout.setVerticalGroup(
            jLabelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelUnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabelDos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setText(" ");

        javax.swing.GroupLayout jLabelDosLayout = new javax.swing.GroupLayout(jLabelDos);
        jLabelDos.setLayout(jLabelDosLayout);
        jLabelDosLayout.setHorizontalGroup(
            jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelDosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelDosLayout.setVerticalGroup(
            jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelDosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLabelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTRes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTRes.setForeground(new java.awt.Color(0, 0, 0));

        jLabelTres.setText(" ");

        javax.swing.GroupLayout jLabelTResLayout = new javax.swing.GroupLayout(jLabelTRes);
        jLabelTRes.setLayout(jLabelTResLayout);
        jLabelTResLayout.setHorizontalGroup(
            jLabelTResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelTResLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jLabelTResLayout.setVerticalGroup(
            jLabelTResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelTResLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTres)
                .addGap(41, 41, 41))
        );

        jLabelCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCuatro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setText(" ");

        javax.swing.GroupLayout jLabelCuatroLayout = new javax.swing.GroupLayout(jLabelCuatro);
        jLabelCuatro.setLayout(jLabelCuatroLayout);
        jLabelCuatroLayout.setHorizontalGroup(
            jLabelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelCuatroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelCuatroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );
        jLabelCuatroLayout.setVerticalGroup(
            jLabelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelCuatroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelCinco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCinco.setForeground(new java.awt.Color(0, 0, 0));

        jLabelCinco.setText(" ");

        javax.swing.GroupLayout jPanelCincoLayout = new javax.swing.GroupLayout(jPanelCinco);
        jPanelCinco.setLayout(jPanelCincoLayout);
        jPanelCincoLayout.setHorizontalGroup(
            jPanelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCincoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelCinco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCincoLayout.setVerticalGroup(
            jPanelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCincoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelCinco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSiete.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSiete.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setText("   ");

        javax.swing.GroupLayout jLabelSieteLayout = new javax.swing.GroupLayout(jLabelSiete);
        jLabelSiete.setLayout(jLabelSieteLayout);
        jLabelSieteLayout.setHorizontalGroup(
            jLabelSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSieteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelSieteLayout.setVerticalGroup(
            jLabelSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSieteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabelSeis.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeis.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSix.setText(" ");

        javax.swing.GroupLayout jLabelSeisLayout = new javax.swing.GroupLayout(jLabelSeis);
        jLabelSeis.setLayout(jLabelSeisLayout);
        jLabelSeisLayout.setHorizontalGroup(
            jLabelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSeisLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelSix)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelSeisLayout.setVerticalGroup(
            jLabelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelSeisLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelSix)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelOcho.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOcho.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setText("  ");

        javax.swing.GroupLayout jLabelOchoLayout = new javax.swing.GroupLayout(jLabelOcho);
        jLabelOcho.setLayout(jLabelOchoLayout);
        jLabelOchoLayout.setHorizontalGroup(
            jLabelOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelOchoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelOchoLayout.setVerticalGroup(
            jLabelOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelOchoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabelNueve.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNueve.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setText(" ");

        javax.swing.GroupLayout jLabelNueveLayout = new javax.swing.GroupLayout(jLabelNueve);
        jLabelNueve.setLayout(jLabelNueveLayout);
        jLabelNueveLayout.setHorizontalGroup(
            jLabelNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelNueveLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLabelNueveLayout.setVerticalGroup(
            jLabelNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelNueveLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCinco;
    private javax.swing.JPanel jLabelCuatro;
    private javax.swing.JPanel jLabelDos;
    private javax.swing.JPanel jLabelNueve;
    private javax.swing.JPanel jLabelOcho;
    private javax.swing.JPanel jLabelSeis;
    private javax.swing.JPanel jLabelSiete;
    private javax.swing.JLabel jLabelSix;
    private javax.swing.JPanel jLabelTRes;
    private javax.swing.JLabel jLabelTres;
    private javax.swing.JPanel jLabelUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCinco;
    // End of variables declaration                   
}
